### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by petrupopescu1**
Implemented dark theme

### CODE REVIEW

**Comment by NacuAndrei** [comment]
Found an issue and I've added it in the issue section

**Comment by NacuAndrei** [comment]
Please push again into dark_theme branch after fixing the issues.

**Comment by petrupopescu1** [comment]
Fixed button by adding new if else statement. Fixed personality test issue by adding themeNotifier to PersonalityTest.dart

**Comment by NacuAndrei** [comment]
Seems ok to me

**Pull request merged**
